FROM parkingplace/ezpz_base:latest

WORKDIR /ezpz/app

RUN pip3 install django &&\
pip3 install djangorestframework &&\
pip3 install django-cors-headers &&\
pip3 install django-rest-knox &&\
pip3 install pandas